# UnbMC, (c) Shadow 2022

# This plugin is an extension of the Unbelievaboat Discord bot and it's economy, 
# allowing you to add more features in your Minecraft server that link with Unbelievaboat!

# Players are required to link their accounts with DiscordSRV to be able to use this plugin.

# ==========================================================================================

# Your API token from the Unbelievaboat website:
api-token: ""

# The information about the symbol you use for your currency:
# The placement should be one of "before" or "after"
symbol: 
  character: "$"
  placement: "before"

# Chat money settings
# Cooldown is in seconds
chat-money:
  cooldown: 15
  min: 1
  max: 5

# Guess the number settings
# Time is in minutes
guess-the-number:
  time:
    min: 2
    max: 5
  payout:
    min: 5
    max: 10
  

# ==========================================================================================

# Debug mode
debug: false
# DO NOT MANUALLY CHANGE THIS
config-version: 1