name: UnbMC
version: ${project.version}
main: com.shadowdev.unbmc.UnbMC
api-version: 1.13
author: thewilloftheshadow
depend: [DiscordSRV]
load: POSTWORLD
website: "https://github.com/thewilloftheshadow/UnbMC"
description: Automatically give and remove Discord roles from players based on their play time within your server.
permissions:
    unbmc.command.balance:
        description: "Allows the user to check their balance."
        default: true
commands:
    balance:
        usage: /balance
        description: "Check your balance."
        permission: unbmc.command.balance
# permissions:
#     unbmc.check:
#         default: true
#         description: Allows the usage of /activity
#     unbmc.lastonline:
#         default: true
#         description: Allows the usage of /lastonline
# commands:
#     activity:
#         usage: /activity
#         permission: unbmc.check
#         description: Check and resync your activity roles
#     lastonline:
#         usage: /lastonline
#         permission: unbmc.lastonline
#         description: Check when you last played on the server
#         arguments:
#             - player:
#                 description: The player to check
#                 type: player
#                 optional: false
